############################################
# When commmenting parameters out, make sure
# that each section still has at least one
# uncommented parameter, otherwise it
# will not get properly parsed.
############################################

input:
    bowtie_index: '/home1/yxiao977/sc1/frip_sm_data/bowtie_index/hg38_mm10/hg38_mm10_index' # Pathway to the bowtie index files, e.g.: **/path_to_index_directory/file_prefix
    ChIP_fastqs: '/home1/yxiao977/sc1/frip_sm_data/download_fastq/erika_test_data' # Pathway to the ChIP fastq files
    Control_fastqs: '/home1/yxiao977/sc1/frip_sm_data/download_fastq/erika_test_input' # Pathway to the input fastq files

common_params:
    processes: 50 # Number of cpus will be used 
    include_spikein: true # Whether the experiment inlcude the 

samtools_params:
    quality: 30 # Quality threshold for filtering bad mapped reads
    distance: 100 # 100 for HiSeq style platforms or about 2500 for NovaSeq ones

spikein_params:
    index_primary: 'mm10' # Name of target species. Leave it blank ('') if spike-in is not included in the experiment
    index_spikein: 'hg38' # Name of spike-in species. Leave it blank ('') if spike-in is not included in the experiment
    binsize: 20 # Size of the bins, in bases, for the output of the bigwig/bedgraph file.

macs2_params:
    no_model: true # If true, then MACS2 will bypass building the shifting model

output:
    ChIP_output_path: '/home1/yxiao977/sc1/frip_sm_data/ChIP_fastqs_maps/erika_test'
    Control_output_path: '/home1/yxiao977/sc1/frip_sm_data/Control_fastqs_maps/erika_test'

##########################################################################################################################################
# Run the pipeline with: 
#       snakemake --use-conda --cores $Ncores --configfile config/config.yml
# To calculate Frip use the python script 
#       python calculate_frip.py --nproc 45 --output-prefix rad21_ctcf --output-directory /home1/yxiao977/sc1/frip_sm_data/frip_result bam bed
##########################################################################################################################################
   
