############################################
# When commmenting parameters out, make sure
# that each section still has at least one
# uncommented parameter, otherwise it
# will not get properly parsed.
############################################

input:
    bowtie_index: '/home1/yxiao977/sc1/frip_sm_data/bowtie_index/mm10_only/mm10' # Pathway to the bowtie index files, e.g.: **/path_to_index_directory/file_prefix
    ChIP_fastqs: '/home1/yxiao977/sc1/frip_sm_data/download_fastq/Hansen_2017' # Pathway to the ChIP fastq files
    metadata: '/home1/yxiao977/sc1/frip_sm_data/download_fastq/Hansen_2017/metadata.txt' # Leave it blank ('') if there is no control samples. Pathway to the metadata.txt that have a table indicates the control sample and the chip sample

common_params:
    processes: 8 # Number of cpus will be used per task. If you set --cores when you run snakemake command line, cores * processes should be <= the number of cpus you have
    include_spikein: false # Whether the experiment inlcude the 

samtools_params:
    quality: 30 # Quality threshold for filtering bad mapped reads
    distance: 100 # 100 for HiSeq style platforms or about 2500 for NovaSeq ones

spikein_params:
    index_primary: '' # Name of target species. Leave it blank ('') if spike-in is not included in the experiment
    index_spikein: '' # Name of spike-in species. Leave it blank ('') if spike-in is not included in the experiment
    binsize: 20 # Size of the bins, in bases, for the output of the bigwig/bedgraph file.

macs2_params:
    broad: false # If true, then MACS2 will call broad peaks (Narrow peaks are typically associated with transcription factors)

output:
    ChIP_output_path: '/home1/yxiao977/sc1/frip_sm_data/ChIP_fastqs_maps/test'

##########################################################################################################################################
# Run the pipeline with: 
#       snakemake --use-conda --cores 5 --configfile config/config.yml
# To calculate Frip use the python script 
#       python calculate_frip.py --nproc 45 pathway/to/metadata/table
##########################################################################################################################################
   
