#########################################
# THIS IS A TYPICAL config.yml TEMPLATE
# most of the settings present here
# are GO for mapping production data
# but nonetheless user must consider
# carefully every presented option
#########################################

#########################################
# When commmenting parameters out, make sure
# that each section still has at least one
# uncommented parameter, otherwise it
# will not get properly parsed.
#########################################



#######################################
# provide paths to your raw input data (fastq-s):
#######################################

input:
    bowtie_index: '/home1/yxiao977/sc1/frip_sm_data/bowtie_index/hg38_mm10/hg38_mm10_index'
    ChIP_fastqs: '/home1/yxiao977/sc1/frip_sm_data/download_fastq'
    Control_fastqs: ''

common_params:
    process: 6
    include_spikein: true

samtools_params:
    quality: 30
    distance: 100

spikein_params:
    index_primary: 'mm10' 
    index_spikein: 'hg38'
    binsize: 20

output:
    ChIP_output_path: '/home1/yxiao977/sc1/frip_sm_data/ChIP_fastqs_maps'
    Control_output_path: '/home1/yxiao977/sc1/frip_sm_data/Control_fastqs_mapsy'
  
   
