parameters:
  dataset : 'Haarhuis_2017' # Name of dataset you want to show on the metadata table
  geo_accession : 'GSE90994' # GEO accession number of dataset you want to show on the metadata table

input:
  path_to_accessions : '/home1/yxiao977/proj/frip_sm_data/download_fastq/Haarhuis_2017/accessions.txt' # Path to a txt file that records a list of sample accessions

output:
  output_directory : '/home1/yxiao977/sc1/test_frip_sm_data/frip_result/Haarhuis_2017/'
