parameters:
  dataset : 'Haarhuis_2017'
  geo_accession : 'GSE90994'

input:
  path_to_accessions : '/home1/yxiao977/proj/frip_sm_data/download_fastq/Haarhuis_2017/accessions.txt'

output:
  output_path : '/home1/yxiao977/sc1/test_frip_sm_data/frip_result/Haarhuis_2017/metadata.txt'
