######## Parameters ####################################################
dataset : 'Haarhuis_2017'
geo_accession : 'GSE90994'
path_to_accessions : '/home1/yxiao977/sc1/frip_sm_data/download_fastq/{dataset}/accessions.txt'

# you need to check if the author upload antibody attribute
contain_antibody_attribute : True

# you need to check how the author names these attributes
condition_key : 'genotype/variation'
antibody_key : 'antibody'
celltype_key : 'cell line'
organism_key : 'organism'

output_path : f'/home1/yxiao977/sc1/frip_sm_data/frip_result/{dataset}/metadata.txt'
########################################################################